# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file holds methods or vaariables used throughiut the application
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
#auto generated by scaffold
