# Creeport version 4 - 5.1.2020
# auto generated by rails - but I have edited
# this file holds elements that can be called or used by the report elements
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class Report < ApplicationRecord
    validates :detailed_description, presence: true, length: { minimum: 100 } #edited to ensure that length requirement is met
#     used to incorporate has-a relationship
    belongs_to :user, :optional => true 

end
#auto generated by scaffold
# I edited this file
