class Report < ApplicationRecord
    validates :detailed_description, presence: true, length: { minimum: 100 } #edited to ensure that length requirement is met
    belongs_to :user, :optional => true

end
#auto generated by scaffold
# I edited this file