# Creeport version 4 - 5.1.2020
# auto generated by rails - edited by devise gem - I have also edited this file
# this file is currently not being used by this prototype version
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
# used to include inheritance -- I added this
  has_many :reports



end
#auto generated by scaffold
#added :confirmable for emil confirmation
