# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file specifies the serializer for the signed and encrypted cookie jars, in Creeport it is auto set to json
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007
# Be sure to restart your server when you modify this file.

# Specify a serializer for the signed and encrypted cookie jars.
# Valid options are :json, :marshal, and :hybrid.
Rails.application.config.action_dispatch.cookies_serializer = :json
