# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file holds sensitive parameters, at thhis implementation it currently only holds the password
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007
# Be sure to restart your server when you modify this file.

# Configure sensitive parameters which will be filtered from the log file.
Rails.application.config.filter_parameters += [:password]
