# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file is currently not being used by this prototype version
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007
# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
