# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file holds information that would be used by the application controller such as methods or encapsulation/inheritnce elements
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class ApplicationController < ActionController::Base
    
end
#auto generated by scaffold
