# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file defines the user page controller functions that are being used 
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class UserPgeController < ApplicationController
  def account_info
  end

  def file_a_report
  end

  def view_all_reports
  end
end
#auto generated by scaffold
