# Creeport version 4 - 5.1.2020
# auto generholds methods and variables that can be called by the welcome controller
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class WelcomeController < ApplicationController
  def index
  end
end
#auto generated by scaffold
