# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file holds classes annd methods to be called 
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end
#auto generated by scaffold
