# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file is currently not being used by this prototype version, not holding any important helper methods to be used throughout application
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

module ApplicationHelper
    # # I added to sort information in columns 
    # def sortable(column, title = nil)
    #     title || column.titleize
    #     direction = column == sort_col && sort_direction == "asc" ? "desc" : "asc"
    #     link_to title, :sort => column, :direction => direction
    # end
end
#auto generated by scaffold
