# Creeport version 4 - 5.1.2020
# auto generated by rails -- I have edited
# this file is used to hold helper methods to be used in relation to report elements
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

module ReportsHelper
    # I added to sort information in columns 
    def sortable(column, title = nil)
        title || column.titleize
        direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
        link_to title, :sort => column, :direction => direction
    end
end
#auto generated by scaffold
