# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file is currently not being used by this prototype version, would be used to hold helper functions for user page
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

module UserPgeHelper
end
#auto generated by scaffold
