# Creeport version 4 - 5.1.2020
# auto generated by devise gem
# this file is used to format action mailer default options
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end
#auto generated by devise gem
