# Creeport version 4 - 5.1.2020
# auto generated by rails 
# this file is currently not being used by this prototype version
# License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

class ApplicationJob < ActiveJob::Base
  # Automatically retry jobs that encountered a deadlock
  # retry_on ActiveRecord::Deadlocked

  # Most jobs are safe to ignore if the underlying records are no longer available
  # discard_on ActiveJob::DeserializationError
end
