// # Creeport version 4 - 5.1.2020
// # auto generated by rails 
// Action Cable provides the framework to deal with WebSockets in Rails.
// You can generate new channels where WebSocket features live using the `rails generate channel` command.
// # License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007



import { createConsumer } from "@rails/actioncable"

export default createConsumer()
