// # Creeport version 4 - 5.1.2020
// # auto generated by rails 
// Load all the channels within this directory and all subdirectories.
// Channel files must be named *_channel.js.
// # License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007



const channels = require.context('.', true, /_channel\.js$/)
channels.keys().forEach(channels)
