// # Creeport version 4 - 5.1.2020
// # auto generated by rails 
// # this file deals with the current environment setting
// # License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

const { environment } = require('@rails/webpacker')

module.exports = environment
