// # Creeport version 4 - 5.1.2020
// # auto generated by rails 
// # this file tests environment settings
// # License  GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007

process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()
